### ISSUE TITLE
Lw 3.2

### ISSUE THREAD

**Issue by elenakuzn** [gtfodmen/web-development#1]
1. в этом коде первый символ может быть например точкой, здесь проверяете именно первый символ
```
                if (preg_match('/[^0-9]/', $identifier[0]))
		{
			echo 'No. Unknown symbol(s) included in identifier.';
		}
```
2.  здесь проверяете весь идентификатор, но сообщение про первый символ
```
$result = preg_match('/^[a-zA-Z0-9]/', $identifier) ? 'No. Incorrect first symbol.' : 'Yes.';
echo $result;
```

**Comment by gtfodmen** [comment]
Поправил, спасибо за точное указание ошибок.

**Comment by elenakuzn** [comment]
1. не исправлено. Теперь вы проверяете символ цифры, но если строка будет начинаеться с "." то ваша программа скажет что идентификатор верный. Надо проверять на то что символ не буква
3. надо разбить весь код на функции.
